# Site settings
title: Kim Jong Tak 위키
url: "https://jameskim1227.github.io"
baseurl: ""
description: >
    Kim Jong Tak 블로그

# My information
email: jameskim1227@gmail.com
author: Kim Jong Tak
profile: Minimalist
github_username: JamesKim1227
comment-support: utterances

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist

permalink: /blog/:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

paginate: 10
paginator_path: "/blog"
paginate_path: "/blog/page:num/"

# Collections
collections:
    wiki:
        output: true
        permalink: /:collection/:path/

# Comment Service
disqus:
  id:
  shortname:
utterances:
  repo:
  issue-term: url
  label: Comment
  branch: master

google_analytics:
  ua:

google_adsense:
  client:

blame: "https://github.com/jameskim1227/jameskim1227.github.io/blame/master/_wiki"
edit: "https://github.com/jameskim1227/jameskim1227.github.io/edit/master/_wiki"
issue: "https://github.com/jameskim1227/jameskim1227.github.io/issues/new"

timezone: "Asia/Seoul"

# https://kramdown.gettalong.org/rdoc/Kramdown/Options.html - smart_quotes
kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]
